use AC_COMPILE_IFELSE rather than running the compiler directly

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -3287,19 +3287,60 @@ for flag in $DESIRED_FLAGS
 do
 	{ echo "$as_me:$LINENO: checking whether $CC accepts $flag" >&5
 echo $ECHO_N "checking whether $CC accepts $flag... $ECHO_C" >&6; }
-	cat >conftest.$ac_ext <<_ACEOF
-int main() { return 0; }
+	cflags="$CFLAGS"
+	CFLAGS="$CFLAGS $flag"
+
+cat >conftest.$ac_ext <<_ACEOF
+
+	    /* confdefs.h.  */
 _ACEOF
-	$CC $CFLAGS $flag -c conftest.c > /dev/null 2> /dev/null
-	if test $? = 0 ; then
-		ADD_CFLAGS="$ADD_CFLAGS $flag"
-		{ echo "$as_me:$LINENO: result: yes" >&5
-echo "${ECHO_T}yes" >&6; };
-	else
-		{ echo "$as_me:$LINENO: result: no" >&5
-echo "${ECHO_T}no" >&6; };
-	fi
-	rm -f conftest.o
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+int
+main ()
+{
+
+  ;
+  return 0;
+}
+
+_ACEOF
+rm -f conftest.$ac_objext
+if { (ac_try="$ac_compile"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_compile") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && {
+	 test -z "$ac_c_werror_flag" ||
+	 test ! -s conftest.err
+       } && test -s conftest.$ac_objext; then
+
+	    { echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6; }
+	    ADD_CFLAGS="$ADD_CFLAGS $flag"
+
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+
+	    { echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6; }
+
+fi
+
+rm -f core conftest.err conftest.$ac_objext conftest.$ac_ext
+	CFLAGS="$cflags"
 done
 
 # setup for cross-compiling mkext
@@ -3356,7 +3397,6 @@ echo "${ECHO_T}not cross compiling" >&6; }
         CC_FOR_BUILD=${CC-cc}
 
 fi
-
 
 ac_ext=c
 ac_cpp='$CPP $CPPFLAGS'
